/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CMS {
cmsActionArgs: CmsActionArgs
cmsData: CmsData
cmsEditorDataContext: CmsEditorDataContext
cmsSaveDataArgs: CmsSaveDataArgs
editorFileContent: EditorFileContent
string: MapStringString
void: Void
[k: string]: unknown
}
export interface CmsActionArgs {
  actionId: string;
  context: CmsEditorDataContext;
  payload: string;
}
export interface CmsEditorDataContext {
  app: string;
  pmv: string;
}
export interface CmsData {
  data: CmsDataObject[];
}
export interface CmsDataObject {
  uri: string;
  values: MapLocaleString;
}
export interface MapLocaleString {
  [k: string]: string;
}
export interface CmsSaveDataArgs {
  context: CmsEditorDataContext;
  data: string;
  directSave: boolean;
}
export interface EditorFileContent {
  content: string;
}
export interface MapStringString {
  [k: string]: string;
}
export interface Void {}
