/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContentObjectType = ("STRING" | "FILE" | "FOLDER")

export interface CMS {
  cmsActionArgs: CmsActionArgs;
  cmsCreateArgs: CmsCreateArgs;
  cmsData: CmsData;
  cmsDataArgs: CmsDataArgs;
  cmsDataObject: CmsDataObject;
  cmsEditorDataContext: CmsEditorDataContext;
  cmsReadArgs: CmsReadArgs;
  string: string[];
  void: Void;
  [k: string]: unknown;
}
export interface CmsActionArgs {
  actionId: "openUrl";
  context: CmsEditorDataContext;
  payload: string;
}
export interface CmsEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}
export interface CmsCreateArgs {
  contentObject: CmsDataObject;
  context: CmsEditorDataContext;
}
export interface CmsDataObject {
  type: ContentObjectType;
  uri: string;
  values: MapStringString;
}
export interface MapStringString {
  [k: string]: string;
}
export interface CmsData {
  context: CmsEditorDataContext;
  data: CmsDataObject[];
  helpUrl: string;
}
export interface CmsDataArgs {
  context: CmsEditorDataContext;
  languageTags: string[];
}
export interface CmsReadArgs {
  context: CmsEditorDataContext;
  uri: string;
}
export interface Void {}
